# Generated by Django 6.0.5 on 2026-05-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisposSensor',
            fields=[
                ('id_dispos_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nb_sensor', models.CharField(max_length=255)),
                ('modelo_iot', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dispos_sensor',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nb_edificio', models.CharField(max_length=255)),
                ('rif', models.IntegerField(unique=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nb_status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='EquipoMonitoreo',
            fields=[
                ('id_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('nb_equipo', models.CharField(max_length=255)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='front.edificio')),
            ],
            options={
                'db_table': 'equipo_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='EquipoSensor',
            fields=[
                ('id_equipo_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_valor_capt', models.FloatField()),
                ('fecha_hora_lect', models.DateTimeField()),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('id_dispos_sensor', models.ForeignKey(db_column='id_dispos_sensor', on_delete=django.db.models.deletion.CASCADE, to='front.dispossensor')),
                ('id_equipo_monitoreo', models.ForeignKey(db_column='id_equipo_monitoreo', on_delete=django.db.models.deletion.CASCADE, to='front.equipomonitoreo')),
            ],
            options={
                'db_table': 'equipo_sensor',
            },
        ),
        migrations.CreateModel(
            name='AccionPrev',
            fields=[
                ('id_accion_prev', models.AutoField(primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=255)),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('accion_preventiva', models.TextField()),
                ('id_dispos_sensor', models.ForeignKey(db_column='id_dispos_sensor', on_delete=django.db.models.deletion.CASCADE, to='front.dispossensor')),
                ('id_equipo_monitoreo', models.ForeignKey(db_column='id_equipo_monitoreo', on_delete=django.db.models.deletion.CASCADE, to='front.equipomonitoreo')),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='front.status')),
            ],
            options={
                'db_table': 'accion_prev',
            },
        ),
        migrations.CreateModel(
            name='StatusEquipoMonitoreo',
            fields=[
                ('id_status_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('id_equipo_monitoreo', models.ForeignKey(db_column='id_equipo_monitoreo', on_delete=django.db.models.deletion.CASCADE, to='front.equipomonitoreo')),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='front.status')),
            ],
            options={
                'db_table': 'status_equipo_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFalla',
            fields=[
                ('id_historico_falla', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('id_equipo_sensor', models.ForeignKey(db_column='id_equipo_sensor', on_delete=django.db.models.deletion.CASCADE, to='front.equiposensor')),
                ('id_status_equipo_monitoreo', models.ForeignKey(db_column='id_status_equipo_monitoreo', on_delete=django.db.models.deletion.CASCADE, to='front.statusequipomonitoreo')),
            ],
            options={
                'db_table': 'historico_falla',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='front.persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('mensaje', models.TextField()),
                ('id_equipo_monitoreo', models.ForeignKey(db_column='id_equipo_monitoreo', on_delete=django.db.models.deletion.CASCADE, to='front.equipomonitoreo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='front.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEdificio',
            fields=[
                ('id_usuario_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='front.edificio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='front.usuario')),
            ],
            options={
                'db_table': 'usuario_edificio',
            },
        ),
    ]
