# Generated by Django 6.0.5 on 2026-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPrev',
            fields=[
                ('id_accion_prev', models.AutoField(primary_key=True, serialize=False)),
                ('parametro', models.TextField(blank=True, null=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('accion_preventiva', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accion_prev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisposSensor',
            fields=[
                ('id_dispos_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nb_sensor', models.TextField(blank=True, null=True)),
                ('modelo_iot', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dispos_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nb_edificio', models.TextField(blank=True, null=True)),
                ('rif', models.IntegerField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoMonitoreo',
            fields=[
                ('id_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('nb_equipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo_monitoreo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoSensor',
            fields=[
                ('id_equipo_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_valor_capt', models.FloatField(blank=True, null=True)),
                ('fecha_hora_lect', models.DateTimeField(blank=True, null=True)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoFalla',
            fields=[
                ('id_historico_falla', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_falla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nb_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusEquipoMonitoreo',
            fields=[
                ('id_status_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'status_equipo_monitoreo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEdificio',
            fields=[
                ('id_usuario_beneficiario', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_edificio',
                'managed': False,
            },
        ),
    ]
